version: '3.8'

services:
  api:
    build:
        context: .                   # The build context is the root of the solution
        dockerfile: /AcmeCorpApi/Dockerfile        # Explicitly specify the Dockerfile location
    container_name: acmecorpapi_docker_compose
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5000:80"   # Map port 5000 on the host to port 80 in the container
    volumes:
      - ./data:/app/data  # Mount a local directory to persist the SQLite database file
    command: >
      /bin/bash -c "dotnet ef database update --project AcmeCorpBusiness --startup-project AcmeCorpApi && dotnet AcmeCorpApi.dll"
  
# Optional: If you need other dependent services, define them here.
